### ISSUE TITLE
cannot create listener due to wrong capitalization caused by system locale

### ISSUE THREAD

**Issue by efeevren** [kshetline/ligatures-limited-intellij#16]
Plugin not working because of following error.

### **IDEA Version**
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### **Operation System**
Ubuntu 21.10 
Linux kernel 5.13.0-39-generic

### **Environment variables:**
LANG=**tr_TR**.UTF-8

### **Failure Log:**
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create class com.shetline.lligatures.LigaturesLimited (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Ligatures Limited, id=com.shetline.ligatures-limited, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210.plugins/Ligatures Limited, version=1.0.4, package=null, isBundled=false), packagePrefix=null, instanceId=21, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:884)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:922)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:177)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:147)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:349)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:141)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.lambda$publish$0(CompositeMessageBus.java:103)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:103)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:176)
	at com.sun.proxy.$Proxy35.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:79)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:176)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.google.gson.JsonParseException: Invalid context name '**PUNCTUATİON**'
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion.applyContextList(LigaturesLimitedSettings.kt:535)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion.access$applyContextList(LigaturesLimitedSettings.kt:86)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion$MyDeserializer.deserializeAux(LigaturesLimitedSettings.kt:267)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion$MyDeserializer.deserialize(LigaturesLimitedSettings.kt:248)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion$MyDeserializer.deserialize(LigaturesLimitedSettings.kt:243)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion.parseJson(LigaturesLimitedSettings.kt:240)
	at com.shetline.lligatures.LigaturesLimitedSettings.loadState(LigaturesLimitedSettings.kt:43)
	at com.shetline.lligatures.LigaturesLimitedSettings.<init>(LigaturesLimitedSettings.kt:24)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:19)
	at com.shetline.lligatures.LigaturesLimitedSettings$Companion.getInstance(LigaturesLimitedSettings.kt:237)
	at com.shetline.lligatures.LigaturesLimited.<init>(LigaturesLimited.kt:55)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	... 23 more

**Comment by kshetline** [comment]
Sorry I've not responded sooner, but I've been unable to replicate this and haven't heard about such a problem from anyone. Feel free to re-open this issue if it's still a problem for you.
